[Access] Use Indexed height when checking payer balance
onflow/flow-emulator pull request #724
Opened 2024-08-07 12:25 UTC by AndriiDiachuk

In this PR new `IndexedHeight` method was added as part of the `Blocks` interface.

Related PR: https://github.com/onflow/flow-go/pull/6292

2024-08-29 15:53 UTC, peterargue commented
@AndriiDiachuk please fix the merge conflict

2024-09-06 13:04 UTC, janezpodhostnik requested changes
Looks good, just that one linting issue.

2024-09-06 13:04 UTC, janezpodhostnik commented on emulator/blockchain.go
>  	"math"
looks like bad linting.

2024-09-27 14:55 UTC, zhangchiqing approved these changes

2024-10-02 14:15 UTC, peterargue commented
replaced by https://github.com/onflow/flow-emulator/pull/755

2024-10-02 14:15 UTC, closed without merging